Attribute VB_Name = "mdSqlite"
'
' Auto-generated by extract.lua at 03/29/16 00:39:21
' Please do not edit manually!
'
Option Explicit
DefObj A-Z

Private Declare Function sqlite3_compileoption_used Lib "debug_sqlite3.dll" (ByVal zOptName As Long) As Long
Private Declare Function sqlite3_compileoption_get Lib "debug_sqlite3.dll" (ByVal N As Long) As Long
Private Declare Function sqlite3_status64 Lib "debug_sqlite3.dll" (ByVal op As Long, ByVal pCurrent As OLE_HANDLE, ByVal pHighwater As OLE_HANDLE, ByVal resetFlag As Long) As Long
Private Declare Function sqlite3_status Lib "debug_sqlite3.dll" (ByVal op As Long, ByVal pCurrent As OLE_HANDLE, ByVal pHighwater As OLE_HANDLE, ByVal resetFlag As Long) As Long
Private Declare Function sqlite3_db_status Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal op As Long, ByVal pCurrent As OLE_HANDLE, ByVal pHighwater As OLE_HANDLE, ByVal resetFlag As Long) As Long
Private Declare Function sqlite3_vfs_find Lib "debug_sqlite3.dll" (ByVal zVfs As Long) As OLE_HANDLE
Private Declare Function sqlite3_vfs_register Lib "debug_sqlite3.dll" (ByVal pVfs As OLE_HANDLE, ByVal makeDflt As Long) As Long
Private Declare Function sqlite3_vfs_unregister Lib "debug_sqlite3.dll" (ByVal pVfs As OLE_HANDLE) As Long
Private Declare Function sqlite3_mutex_alloc Lib "debug_sqlite3.dll" (ByVal id As Long) As OLE_HANDLE
Private Declare Function sqlite3_mutex_free Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As Long
Private Declare Function sqlite3_mutex_enter Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As Long
Private Declare Function sqlite3_mutex_try Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As Long
Private Declare Function sqlite3_mutex_leave Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As Long
Private Declare Function sqlite3_release_memory Lib "debug_sqlite3.dll" (ByVal n As Long) As Long
Private Declare Function sqlite3_memory_alarm Lib "debug_sqlite3.dll" (ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE, ByVal iThreshold As Currency) As Long
Private Declare Function sqlite3_soft_heap_limit64 Lib "debug_sqlite3.dll" (ByVal n As Currency) As Currency
Private Declare Function sqlite3_soft_heap_limit Lib "debug_sqlite3.dll" (ByVal n As Long) As Long
Private Declare Function sqlite3_memory_used Lib "debug_sqlite3.dll" () As Currency
Private Declare Function sqlite3_memory_highwater Lib "debug_sqlite3.dll" (ByVal resetFlag As Long) As Currency
Private Declare Function sqlite3_malloc Lib "debug_sqlite3.dll" (ByVal n As Long) As OLE_HANDLE
Private Declare Function sqlite3_malloc64 Lib "debug_sqlite3.dll" (ByVal n As Currency) As OLE_HANDLE
Private Declare Function sqlite3_msize Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As Currency
Private Declare Function sqlite3_free Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As Long
Private Declare Function sqlite3_realloc Lib "debug_sqlite3.dll" (ByVal pOld As OLE_HANDLE, ByVal n As Long) As OLE_HANDLE
Private Declare Function sqlite3_realloc64 Lib "debug_sqlite3.dll" (ByVal pOld As OLE_HANDLE, ByVal n As Currency) As OLE_HANDLE
Private Declare Function sqlite3_vmprintf Lib "debug_sqlite3.dll" (ByVal zFormat As Long, ByVal ap As OLE_HANDLE) As Long
Private Declare Function sqlite3_vsnprintf Lib "debug_sqlite3.dll" (ByVal n As Long, ByVal zBuf As Long, ByVal zFormat As Long, ByVal ap As OLE_HANDLE) As Long
Private Declare Function sqlite3_randomness Lib "debug_sqlite3.dll" (ByVal N As Long, ByVal pBuf As OLE_HANDLE) As Long
Private Declare Function sqlite3_stricmp Lib "debug_sqlite3.dll" (ByVal zLeft As Long, ByVal zRight As Long) As Long
Private Declare Function sqlite3_strnicmp Lib "debug_sqlite3.dll" (ByVal zLeft As Long, ByVal zRight As Long, ByVal N As Long) As Long
Private Declare Function sqlite3_os_init Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_os_end Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_win32_write_debug Lib "debug_sqlite3.dll" (ByVal zBuf As Long, ByVal nBuf As Long) As Long
Private Declare Function sqlite3_win32_sleep Lib "debug_sqlite3.dll" (ByVal milliseconds As Long) As Long
Private Declare Function sqlite3_win32_is_nt Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_win32_mbcs_to_utf8 Lib "debug_sqlite3.dll" (ByVal zFilename As Long) As Long
Private Declare Function sqlite3_win32_utf8_to_mbcs Lib "debug_sqlite3.dll" (ByVal zFilename As Long) As Long
Private Declare Function sqlite3_win32_set_directory Lib "debug_sqlite3.dll" (ByVal type_ As Long, ByVal zValue As Long) As Long
Private Declare Function sqlite3_enable_shared_cache Lib "debug_sqlite3.dll" (ByVal enable As Long) As Long
Private Declare Function sqlite3_backup_init Lib "debug_sqlite3.dll" (ByVal pDestDb As OLE_HANDLE, ByVal zDestDb As Long, ByVal pSrcDb As OLE_HANDLE, ByVal zSrcDb As Long) As OLE_HANDLE
Private Declare Function sqlite3_backup_step Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE, ByVal nPage As Long) As Long
Private Declare Function sqlite3_backup_finish Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As Long
Private Declare Function sqlite3_backup_remaining Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As Long
Private Declare Function sqlite3_backup_pagecount Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As Long
Private Declare Function sqlite3_sql Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_expired Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_finalize Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_reset Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_clear_bindings Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_value_blob Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_value_bytes Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As Long
Private Declare Function sqlite3_value_bytes16 Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As Long
Private Declare Function sqlite3_value_double Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As Double
Private Declare Function sqlite3_value_int Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As Long
Private Declare Function sqlite3_value_int64 Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As Currency
Private Declare Function sqlite3_value_subtype Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As Long
Private Declare Function sqlite3_value_text Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_value_text16 Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_value_text16be Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_value_text16le Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_value_type Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As Long
Private Declare Function sqlite3_value_dup Lib "debug_sqlite3.dll" (ByVal pOrig As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_value_free Lib "debug_sqlite3.dll" (ByVal pOld As OLE_HANDLE) As Long
Private Declare Function sqlite3_result_blob Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_result_blob64 Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Currency, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_result_double Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal rVal As Double) As Long
Private Declare Function sqlite3_result_error Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal z As Long, ByVal n As Long) As Long
Private Declare Function sqlite3_result_error16 Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long) As Long
Private Declare Function sqlite3_result_int Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal iVal As Long) As Long
Private Declare Function sqlite3_result_int64 Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal iVal As Currency) As Long
Private Declare Function sqlite3_result_null Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE) As Long
Private Declare Function sqlite3_result_subtype Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal eSubtype As Long) As Long
Private Declare Function sqlite3_result_text Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal z As Long, ByVal n As Long, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_result_text64 Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal z As Long, ByVal n As Currency, ByVal xDel As OLE_HANDLE, ByVal enc As Long) As Long
Private Declare Function sqlite3_result_text16 Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_result_text16be Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_result_text16le Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_result_value Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal pValue As OLE_HANDLE) As Long
Private Declare Function sqlite3_result_zeroblob Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal n As Long) As Long
Private Declare Function sqlite3_result_zeroblob64 Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal n As Currency) As Long
Private Declare Function sqlite3_result_error_code Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal errCode As Long) As Long
Private Declare Function sqlite3_result_error_toobig Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE) As Long
Private Declare Function sqlite3_result_error_nomem Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE) As Long
Private Declare Function sqlite3_step Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_user_data Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_context_db_handle Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_aggregate_context Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE, ByVal nByte As Long) As OLE_HANDLE
Private Declare Function sqlite3_get_auxdata Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal iArg As Long) As OLE_HANDLE
Private Declare Function sqlite3_set_auxdata Lib "debug_sqlite3.dll" (ByVal pCtx As OLE_HANDLE, ByVal iArg As Long, ByVal pAux As OLE_HANDLE, ByVal xDelete As OLE_HANDLE) As Long
Private Declare Function sqlite3_aggregate_count Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE) As Long
Private Declare Function sqlite3_column_count Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_data_count Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_column_blob Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As OLE_HANDLE
Private Declare Function sqlite3_column_bytes Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
Private Declare Function sqlite3_column_bytes16 Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
Private Declare Function sqlite3_column_double Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Double
Private Declare Function sqlite3_column_int Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
Private Declare Function sqlite3_column_int64 Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Currency
Private Declare Function sqlite3_column_text Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As OLE_HANDLE
Private Declare Function sqlite3_column_value Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As OLE_HANDLE
Private Declare Function sqlite3_column_text16 Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As OLE_HANDLE
Private Declare Function sqlite3_column_type Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
Private Declare Function sqlite3_column_name Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal N As Long) As Long
Private Declare Function sqlite3_column_name16 Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal N As Long) As OLE_HANDLE
Private Declare Function sqlite3_column_decltype Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal N As Long) As Long
Private Declare Function sqlite3_column_decltype16 Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal N As Long) As OLE_HANDLE
Private Declare Function sqlite3_bind_blob Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal zData As OLE_HANDLE, ByVal nData As Long, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_bind_blob64 Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal zData As OLE_HANDLE, ByVal nData As Currency, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_bind_double Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal rValue As Double) As Long
Private Declare Function sqlite3_bind_int Lib "debug_sqlite3.dll" (ByVal p As OLE_HANDLE, ByVal i As Long, ByVal iValue As Long) As Long
Private Declare Function sqlite3_bind_int64 Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal iValue As Currency) As Long
Private Declare Function sqlite3_bind_null Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
Private Declare Function sqlite3_bind_text Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal zData As Long, ByVal nData As Long, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_bind_text64 Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal zData As Long, ByVal nData As Currency, ByVal xDel As OLE_HANDLE, ByVal enc As Long) As Long
Private Declare Function sqlite3_bind_text16 Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal zData As OLE_HANDLE, ByVal nData As Long, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_bind_value Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal pValue As OLE_HANDLE) As Long
Private Declare Function sqlite3_bind_zeroblob Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal n As Long) As Long
Private Declare Function sqlite3_bind_zeroblob64 Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal n As Currency) As Long
Private Declare Function sqlite3_bind_parameter_count Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_bind_parameter_name Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
Private Declare Function sqlite3_bind_parameter_index Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal zName As Long) As Long
Private Declare Function sqlite3_transfer_bindings Lib "debug_sqlite3.dll" (ByVal pFromStmt As OLE_HANDLE, ByVal pToStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_db_handle Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_stmt_readonly Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_stmt_busy Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE) As Long
Private Declare Function sqlite3_next_stmt Lib "debug_sqlite3.dll" (ByVal pDb As OLE_HANDLE, ByVal pStmt As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_stmt_status Lib "debug_sqlite3.dll" (ByVal pStmt As OLE_HANDLE, ByVal op As Long, ByVal resetFlag As Long) As Long
Private Declare Function sqlite3_value_numeric_type Lib "debug_sqlite3.dll" (ByVal pVal As OLE_HANDLE) As Long
Private Declare Function sqlite3_blob_open Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zDb As Long, ByVal zTable As Long, ByVal zColumn As Long, ByVal iRow As Currency, ByVal flags As Long, ByVal ppBlob As OLE_HANDLE) As Long
Private Declare Function sqlite3_blob_close Lib "debug_sqlite3.dll" (ByVal pBlob As OLE_HANDLE) As Long
Private Declare Function sqlite3_blob_read Lib "debug_sqlite3.dll" (ByVal pBlob As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal iOffset As Long) As Long
Private Declare Function sqlite3_blob_write Lib "debug_sqlite3.dll" (ByVal pBlob As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal iOffset As Long) As Long
Private Declare Function sqlite3_blob_bytes Lib "debug_sqlite3.dll" (ByVal pBlob As OLE_HANDLE) As Long
Private Declare Function sqlite3_blob_reopen Lib "debug_sqlite3.dll" (ByVal pBlob As OLE_HANDLE, ByVal iRow As Currency) As Long
Private Declare Function sqlite3_set_authorizer Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal xAuth As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As Long
Private Declare Function sqlite3_strglob Lib "debug_sqlite3.dll" (ByVal zGlobPattern As Long, ByVal zString As Long) As Long
Private Declare Function sqlite3_strlike Lib "debug_sqlite3.dll" (ByVal zPattern As Long, ByVal zStr As Long, ByVal esc As Long) As Long
Private Declare Function sqlite3_exec Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zSql As Long, ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE, ByVal pzErrMsg As OLE_HANDLE) As Long
Private Declare Function sqlite3_load_extension Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zFile As Long, ByVal zProc As Long, ByVal pzErrMsg As OLE_HANDLE) As Long
Private Declare Function sqlite3_enable_load_extension Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal onoff As Long) As Long
Private Declare Function sqlite3_auto_extension Lib "debug_sqlite3.dll" (ByVal xInit As OLE_HANDLE) As Long
Private Declare Function sqlite3_cancel_auto_extension Lib "debug_sqlite3.dll" (ByVal xInit As OLE_HANDLE) As Long
Private Declare Function sqlite3_reset_auto_extension Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_prepare Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zSql As Long, ByVal nBytes As Long, ByVal ppStmt As OLE_HANDLE, ByVal pzTail As OLE_HANDLE) As Long
Private Declare Function sqlite3_prepare_v2 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zSql As Long, ByVal nBytes As Long, ByVal ppStmt As OLE_HANDLE, ByVal pzTail As OLE_HANDLE) As Long
Private Declare Function sqlite3_prepare16 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zSql As OLE_HANDLE, ByVal nBytes As Long, ByVal ppStmt As OLE_HANDLE, ByVal pzTail As OLE_HANDLE) As Long
Private Declare Function sqlite3_prepare16_v2 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zSql As OLE_HANDLE, ByVal nBytes As Long, ByVal ppStmt As OLE_HANDLE, ByVal pzTail As OLE_HANDLE) As Long
Private Declare Function sqlite3_get_table Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zSql As Long, ByVal pazResult As OLE_HANDLE, ByVal pnRow As OLE_HANDLE, ByVal pnColumn As OLE_HANDLE, ByVal pzErrMsg As OLE_HANDLE) As Long
Private Declare Function sqlite3_free_table Lib "debug_sqlite3.dll" (ByVal azResult As OLE_HANDLE) As Long
Private Declare Function sqlite3_create_module Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zName As Long, ByVal pModule As OLE_HANDLE, ByVal pAux As OLE_HANDLE) As Long
Private Declare Function sqlite3_create_module_v2 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zName As Long, ByVal pModule As OLE_HANDLE, ByVal pAux As OLE_HANDLE, ByVal xDestroy As OLE_HANDLE) As Long
Private Declare Function sqlite3_declare_vtab Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zCreateTable As Long) As Long
Private Declare Function sqlite3_vtab_on_conflict Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_complete Lib "debug_sqlite3.dll" (ByVal zSql As Long) As Long
Private Declare Function sqlite3_complete16 Lib "debug_sqlite3.dll" (ByVal zSql As OLE_HANDLE) As Long
Private Declare Function sqlite3_libversion Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_sourceid Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_libversion_number Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_threadsafe Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_initialize Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_shutdown Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_db_mutex Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_db_release_memory Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_db_cacheflush Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_last_insert_rowid Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Currency
Private Declare Function sqlite3_changes Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_total_changes Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_close Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_close_v2 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_busy_handler Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal xBusy As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As Long
Private Declare Function sqlite3_progress_handler Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal nOps As Long, ByVal xProgress As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As Long
Private Declare Function sqlite3_busy_timeout Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal ms As Long) As Long
Private Declare Function sqlite3_interrupt Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_create_function Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zFunc As Long, ByVal nArg As Long, ByVal enc As Long, ByVal p As OLE_HANDLE, ByVal xSFunc As OLE_HANDLE, ByVal xStep As OLE_HANDLE, ByVal xFinal As OLE_HANDLE) As Long
Private Declare Function sqlite3_create_function_v2 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zFunc As Long, ByVal nArg As Long, ByVal enc As Long, ByVal p As OLE_HANDLE, ByVal xSFunc As OLE_HANDLE, ByVal xStep As OLE_HANDLE, ByVal xFinal As OLE_HANDLE, ByVal xDestroy As OLE_HANDLE) As Long
Private Declare Function sqlite3_create_function16 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zFunctionName As OLE_HANDLE, ByVal nArg As Long, ByVal eTextRep As Long, ByVal p As OLE_HANDLE, ByVal xSFunc As OLE_HANDLE, ByVal xStep As OLE_HANDLE, ByVal xFinal As OLE_HANDLE) As Long
Private Declare Function sqlite3_overload_function Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zName As Long, ByVal nArg As Long) As Long
Private Declare Function sqlite3_trace Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal xTrace As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_profile Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal xProfile As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_commit_hook Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_update_hook Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_rollback_hook Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_wal_autocheckpoint Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal nFrame As Long) As Long
Private Declare Function sqlite3_wal_hook Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_wal_checkpoint_v2 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zDb As Long, ByVal eMode As Long, ByVal pnLog As OLE_HANDLE, ByVal pnCkpt As OLE_HANDLE) As Long
Private Declare Function sqlite3_wal_checkpoint Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zDb As Long) As Long
Private Declare Function sqlite3_errmsg Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_errmsg16 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As OLE_HANDLE
Private Declare Function sqlite3_errcode Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_extended_errcode Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_errstr Lib "debug_sqlite3.dll" (ByVal rc As Long) As Long
Private Declare Function sqlite3_limit Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal limitId As Long, ByVal newLimit As Long) As Long
Private Declare Function sqlite3_open Lib "debug_sqlite3.dll" (ByVal zFilename As Long, ByVal ppDb As OLE_HANDLE) As Long
Private Declare Function sqlite3_open_v2 Lib "debug_sqlite3.dll" (ByVal filename As Long, ByVal ppDb As OLE_HANDLE, ByVal flags As Long, ByVal zVfs As Long) As Long
Private Declare Function sqlite3_open16 Lib "debug_sqlite3.dll" (ByVal zFilename As OLE_HANDLE, ByVal ppDb As OLE_HANDLE) As Long
Private Declare Function sqlite3_create_collation Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zName As Long, ByVal enc As Long, ByVal pCtx As OLE_HANDLE, ByVal xCompare As OLE_HANDLE) As Long
Private Declare Function sqlite3_create_collation_v2 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zName As Long, ByVal enc As Long, ByVal pCtx As OLE_HANDLE, ByVal xCompare As OLE_HANDLE, ByVal xDel As OLE_HANDLE) As Long
Private Declare Function sqlite3_create_collation16 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zName As OLE_HANDLE, ByVal enc As Long, ByVal pCtx As OLE_HANDLE, ByVal xCompare As OLE_HANDLE) As Long
Private Declare Function sqlite3_collation_needed Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal pCollNeededArg As OLE_HANDLE, ByVal xCollNeeded As OLE_HANDLE) As Long
Private Declare Function sqlite3_collation_needed16 Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal pCollNeededArg As OLE_HANDLE, ByVal xCollNeeded16 As OLE_HANDLE) As Long
Private Declare Function sqlite3_global_recover Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_get_autocommit Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE) As Long
Private Declare Function sqlite3_thread_cleanup Lib "debug_sqlite3.dll" () As Long
Private Declare Function sqlite3_table_column_metadata Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zDbName As Long, ByVal zTableName As Long, ByVal zColumnName As Long, ByVal pzDataType As OLE_HANDLE, ByVal pzCollSeq As OLE_HANDLE, ByVal pNotNull As OLE_HANDLE, ByVal pPrimaryKey As OLE_HANDLE, ByVal pAutoinc As OLE_HANDLE) As Long
Private Declare Function sqlite3_sleep Lib "debug_sqlite3.dll" (ByVal ms As Long) As Long
Private Declare Function sqlite3_extended_result_codes Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal onoff As Long) As Long
Private Declare Function sqlite3_file_control Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zDbName As Long, ByVal op As Long, ByVal pArg As OLE_HANDLE) As Long
Private Declare Function sqlite3_uri_parameter Lib "debug_sqlite3.dll" (ByVal zFilename As Long, ByVal zParam As Long) As Long
Private Declare Function sqlite3_uri_boolean Lib "debug_sqlite3.dll" (ByVal zFilename As Long, ByVal zParam As Long, ByVal bDflt As Long) As Long
Private Declare Function sqlite3_uri_int64 Lib "debug_sqlite3.dll" (ByVal zFilename As Long, ByVal zParam As Long, ByVal bDflt As Currency) As Currency
Private Declare Function sqlite3_db_filename Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zDbName As Long) As Long
Private Declare Function sqlite3_db_readonly Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zDbName As Long) As Long
Private Declare Function sqlite3_rtree_geometry_callback Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zGeom As Long, ByVal xGeom As OLE_HANDLE, ByVal pContext As OLE_HANDLE) As Long
Private Declare Function sqlite3_rtree_query_callback Lib "debug_sqlite3.dll" (ByVal db As OLE_HANDLE, ByVal zQueryFunc As Long, ByVal xQueryFunc As OLE_HANDLE, ByVal pContext As OLE_HANDLE, ByVal xDestructor As OLE_HANDLE) As Long

Public Function vbsqlite3_compileoption_used(ByVal zOptName As Long) As Long
    vbsqlite3_compileoption_used = sqlite3_compileoption_used(zOptName)
End Function

Public Function vbsqlite3_compileoption_get(ByVal N As Long) As Long
    vbsqlite3_compileoption_get = sqlite3_compileoption_get(N)
End Function

Public Function vbsqlite3_status64(ByVal op As Long, ByVal pCurrent As OLE_HANDLE, ByVal pHighwater As OLE_HANDLE, ByVal resetFlag As Long) As Long
    vbsqlite3_status64 = sqlite3_status64(op, pCurrent, pHighwater, resetFlag)
End Function

Public Function vbsqlite3_status(ByVal op As Long, ByVal pCurrent As OLE_HANDLE, ByVal pHighwater As OLE_HANDLE, ByVal resetFlag As Long) As Long
    vbsqlite3_status = sqlite3_status(op, pCurrent, pHighwater, resetFlag)
End Function

Public Function vbsqlite3_db_status(ByVal db As OLE_HANDLE, ByVal op As Long, ByVal pCurrent As OLE_HANDLE, ByVal pHighwater As OLE_HANDLE, ByVal resetFlag As Long) As Long
    vbsqlite3_db_status = sqlite3_db_status(db, op, pCurrent, pHighwater, resetFlag)
End Function

Public Function vbsqlite3_vfs_find(ByVal zVfs As Long) As OLE_HANDLE
    vbsqlite3_vfs_find = sqlite3_vfs_find(zVfs)
End Function

Public Function vbsqlite3_vfs_register(ByVal pVfs As OLE_HANDLE, ByVal makeDflt As Long) As Long
    vbsqlite3_vfs_register = sqlite3_vfs_register(pVfs, makeDflt)
End Function

Public Function vbsqlite3_vfs_unregister(ByVal pVfs As OLE_HANDLE) As Long
    vbsqlite3_vfs_unregister = sqlite3_vfs_unregister(pVfs)
End Function

Public Function vbsqlite3_mutex_alloc(ByVal id As Long) As OLE_HANDLE
    vbsqlite3_mutex_alloc = sqlite3_mutex_alloc(id)
End Function

Public Function vbsqlite3_mutex_free(ByVal p As OLE_HANDLE) As Long
    vbsqlite3_mutex_free = sqlite3_mutex_free(p)
End Function

Public Function vbsqlite3_mutex_enter(ByVal p As OLE_HANDLE) As Long
    vbsqlite3_mutex_enter = sqlite3_mutex_enter(p)
End Function

Public Function vbsqlite3_mutex_try(ByVal p As OLE_HANDLE) As Long
    vbsqlite3_mutex_try = sqlite3_mutex_try(p)
End Function

Public Function vbsqlite3_mutex_leave(ByVal p As OLE_HANDLE) As Long
    vbsqlite3_mutex_leave = sqlite3_mutex_leave(p)
End Function

Public Function vbsqlite3_release_memory(ByVal n As Long) As Long
    vbsqlite3_release_memory = sqlite3_release_memory(n)
End Function

Public Function vbsqlite3_memory_alarm(ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE, ByVal iThreshold As Currency) As Long
    vbsqlite3_memory_alarm = sqlite3_memory_alarm(xCallback, pArg, iThreshold)
End Function

Public Function vbsqlite3_soft_heap_limit64(ByVal n As Currency) As Currency
    vbsqlite3_soft_heap_limit64 = sqlite3_soft_heap_limit64(n)
End Function

Public Function vbsqlite3_soft_heap_limit(ByVal n As Long) As Long
    vbsqlite3_soft_heap_limit = sqlite3_soft_heap_limit(n)
End Function

Public Function vbsqlite3_memory_used() As Currency
    vbsqlite3_memory_used = sqlite3_memory_used()
End Function

Public Function vbsqlite3_memory_highwater(ByVal resetFlag As Long) As Currency
    vbsqlite3_memory_highwater = sqlite3_memory_highwater(resetFlag)
End Function

Public Function vbsqlite3_malloc(ByVal n As Long) As OLE_HANDLE
    vbsqlite3_malloc = sqlite3_malloc(n)
End Function

Public Function vbsqlite3_malloc64(ByVal n As Currency) As OLE_HANDLE
    vbsqlite3_malloc64 = sqlite3_malloc64(n)
End Function

Public Function vbsqlite3_msize(ByVal p As OLE_HANDLE) As Currency
    vbsqlite3_msize = sqlite3_msize(p)
End Function

Public Function vbsqlite3_free(ByVal p As OLE_HANDLE) As Long
    vbsqlite3_free = sqlite3_free(p)
End Function

Public Function vbsqlite3_realloc(ByVal pOld As OLE_HANDLE, ByVal n As Long) As OLE_HANDLE
    vbsqlite3_realloc = sqlite3_realloc(pOld, n)
End Function

Public Function vbsqlite3_realloc64(ByVal pOld As OLE_HANDLE, ByVal n As Currency) As OLE_HANDLE
    vbsqlite3_realloc64 = sqlite3_realloc64(pOld, n)
End Function

Public Function vbsqlite3_vmprintf(ByVal zFormat As Long, ByVal ap As OLE_HANDLE) As Long
    vbsqlite3_vmprintf = sqlite3_vmprintf(zFormat, ap)
End Function

Public Function vbsqlite3_vsnprintf(ByVal n As Long, ByVal zBuf As Long, ByVal zFormat As Long, ByVal ap As OLE_HANDLE) As Long
    vbsqlite3_vsnprintf = sqlite3_vsnprintf(n, zBuf, zFormat, ap)
End Function

Public Function vbsqlite3_randomness(ByVal N As Long, ByVal pBuf As OLE_HANDLE) As Long
    vbsqlite3_randomness = sqlite3_randomness(N, pBuf)
End Function

Public Function vbsqlite3_stricmp(ByVal zLeft As Long, ByVal zRight As Long) As Long
    vbsqlite3_stricmp = sqlite3_stricmp(zLeft, zRight)
End Function

Public Function vbsqlite3_strnicmp(ByVal zLeft As Long, ByVal zRight As Long, ByVal N As Long) As Long
    vbsqlite3_strnicmp = sqlite3_strnicmp(zLeft, zRight, N)
End Function

Public Function vbsqlite3_os_init() As Long
    vbsqlite3_os_init = sqlite3_os_init()
End Function

Public Function vbsqlite3_os_end() As Long
    vbsqlite3_os_end = sqlite3_os_end()
End Function

Public Function vbsqlite3_win32_write_debug(ByVal zBuf As Long, ByVal nBuf As Long) As Long
    vbsqlite3_win32_write_debug = sqlite3_win32_write_debug(zBuf, nBuf)
End Function

Public Function vbsqlite3_win32_sleep(ByVal milliseconds As Long) As Long
    vbsqlite3_win32_sleep = sqlite3_win32_sleep(milliseconds)
End Function

Public Function vbsqlite3_win32_is_nt() As Long
    vbsqlite3_win32_is_nt = sqlite3_win32_is_nt()
End Function

Public Function vbsqlite3_win32_mbcs_to_utf8(ByVal zFilename As Long) As Long
    vbsqlite3_win32_mbcs_to_utf8 = sqlite3_win32_mbcs_to_utf8(zFilename)
End Function

Public Function vbsqlite3_win32_utf8_to_mbcs(ByVal zFilename As Long) As Long
    vbsqlite3_win32_utf8_to_mbcs = sqlite3_win32_utf8_to_mbcs(zFilename)
End Function

Public Function vbsqlite3_win32_set_directory(ByVal type_ As Long, ByVal zValue As Long) As Long
    vbsqlite3_win32_set_directory = sqlite3_win32_set_directory(type_, zValue)
End Function

Public Function vbsqlite3_enable_shared_cache(ByVal enable As Long) As Long
    vbsqlite3_enable_shared_cache = sqlite3_enable_shared_cache(enable)
End Function

Public Function vbsqlite3_backup_init(ByVal pDestDb As OLE_HANDLE, ByVal zDestDb As Long, ByVal pSrcDb As OLE_HANDLE, ByVal zSrcDb As Long) As OLE_HANDLE
    vbsqlite3_backup_init = sqlite3_backup_init(pDestDb, zDestDb, pSrcDb, zSrcDb)
End Function

Public Function vbsqlite3_backup_step(ByVal p As OLE_HANDLE, ByVal nPage As Long) As Long
    vbsqlite3_backup_step = sqlite3_backup_step(p, nPage)
End Function

Public Function vbsqlite3_backup_finish(ByVal p As OLE_HANDLE) As Long
    vbsqlite3_backup_finish = sqlite3_backup_finish(p)
End Function

Public Function vbsqlite3_backup_remaining(ByVal p As OLE_HANDLE) As Long
    vbsqlite3_backup_remaining = sqlite3_backup_remaining(p)
End Function

Public Function vbsqlite3_backup_pagecount(ByVal p As OLE_HANDLE) As Long
    vbsqlite3_backup_pagecount = sqlite3_backup_pagecount(p)
End Function

Public Function vbsqlite3_sql(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_sql = sqlite3_sql(pStmt)
End Function

Public Function vbsqlite3_expired(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_expired = sqlite3_expired(pStmt)
End Function

Public Function vbsqlite3_finalize(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_finalize = sqlite3_finalize(pStmt)
End Function

Public Function vbsqlite3_reset(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_reset = sqlite3_reset(pStmt)
End Function

Public Function vbsqlite3_clear_bindings(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_clear_bindings = sqlite3_clear_bindings(pStmt)
End Function

Public Function vbsqlite3_value_blob(ByVal pVal As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_value_blob = sqlite3_value_blob(pVal)
End Function

Public Function vbsqlite3_value_bytes(ByVal pVal As OLE_HANDLE) As Long
    vbsqlite3_value_bytes = sqlite3_value_bytes(pVal)
End Function

Public Function vbsqlite3_value_bytes16(ByVal pVal As OLE_HANDLE) As Long
    vbsqlite3_value_bytes16 = sqlite3_value_bytes16(pVal)
End Function

Public Function vbsqlite3_value_double(ByVal pVal As OLE_HANDLE) As Double
    vbsqlite3_value_double = sqlite3_value_double(pVal)
End Function

Public Function vbsqlite3_value_int(ByVal pVal As OLE_HANDLE) As Long
    vbsqlite3_value_int = sqlite3_value_int(pVal)
End Function

Public Function vbsqlite3_value_int64(ByVal pVal As OLE_HANDLE) As Currency
    vbsqlite3_value_int64 = sqlite3_value_int64(pVal)
End Function

Public Function vbsqlite3_value_subtype(ByVal pVal As OLE_HANDLE) As Long
    vbsqlite3_value_subtype = sqlite3_value_subtype(pVal)
End Function

Public Function vbsqlite3_value_text(ByVal pVal As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_value_text = sqlite3_value_text(pVal)
End Function

Public Function vbsqlite3_value_text16(ByVal pVal As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_value_text16 = sqlite3_value_text16(pVal)
End Function

Public Function vbsqlite3_value_text16be(ByVal pVal As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_value_text16be = sqlite3_value_text16be(pVal)
End Function

Public Function vbsqlite3_value_text16le(ByVal pVal As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_value_text16le = sqlite3_value_text16le(pVal)
End Function

Public Function vbsqlite3_value_type(ByVal pVal As OLE_HANDLE) As Long
    vbsqlite3_value_type = sqlite3_value_type(pVal)
End Function

Public Function vbsqlite3_value_dup(ByVal pOrig As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_value_dup = sqlite3_value_dup(pOrig)
End Function

Public Function vbsqlite3_value_free(ByVal pOld As OLE_HANDLE) As Long
    vbsqlite3_value_free = sqlite3_value_free(pOld)
End Function

Public Function vbsqlite3_result_blob(ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_result_blob = sqlite3_result_blob(pCtx, z, n, xDel)
End Function

Public Function vbsqlite3_result_blob64(ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Currency, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_result_blob64 = sqlite3_result_blob64(pCtx, z, n, xDel)
End Function

Public Function vbsqlite3_result_double(ByVal pCtx As OLE_HANDLE, ByVal rVal As Double) As Long
    vbsqlite3_result_double = sqlite3_result_double(pCtx, rVal)
End Function

Public Function vbsqlite3_result_error(ByVal pCtx As OLE_HANDLE, ByVal z As Long, ByVal n As Long) As Long
    vbsqlite3_result_error = sqlite3_result_error(pCtx, z, n)
End Function

Public Function vbsqlite3_result_error16(ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long) As Long
    vbsqlite3_result_error16 = sqlite3_result_error16(pCtx, z, n)
End Function

Public Function vbsqlite3_result_int(ByVal pCtx As OLE_HANDLE, ByVal iVal As Long) As Long
    vbsqlite3_result_int = sqlite3_result_int(pCtx, iVal)
End Function

Public Function vbsqlite3_result_int64(ByVal pCtx As OLE_HANDLE, ByVal iVal As Currency) As Long
    vbsqlite3_result_int64 = sqlite3_result_int64(pCtx, iVal)
End Function

Public Function vbsqlite3_result_null(ByVal pCtx As OLE_HANDLE) As Long
    vbsqlite3_result_null = sqlite3_result_null(pCtx)
End Function

Public Function vbsqlite3_result_subtype(ByVal pCtx As OLE_HANDLE, ByVal eSubtype As Long) As Long
    vbsqlite3_result_subtype = sqlite3_result_subtype(pCtx, eSubtype)
End Function

Public Function vbsqlite3_result_text(ByVal pCtx As OLE_HANDLE, ByVal z As Long, ByVal n As Long, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_result_text = sqlite3_result_text(pCtx, z, n, xDel)
End Function

Public Function vbsqlite3_result_text64(ByVal pCtx As OLE_HANDLE, ByVal z As Long, ByVal n As Currency, ByVal xDel As OLE_HANDLE, ByVal enc As Long) As Long
    vbsqlite3_result_text64 = sqlite3_result_text64(pCtx, z, n, xDel, enc)
End Function

Public Function vbsqlite3_result_text16(ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_result_text16 = sqlite3_result_text16(pCtx, z, n, xDel)
End Function

Public Function vbsqlite3_result_text16be(ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_result_text16be = sqlite3_result_text16be(pCtx, z, n, xDel)
End Function

Public Function vbsqlite3_result_text16le(ByVal pCtx As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_result_text16le = sqlite3_result_text16le(pCtx, z, n, xDel)
End Function

Public Function vbsqlite3_result_value(ByVal pCtx As OLE_HANDLE, ByVal pValue As OLE_HANDLE) As Long
    vbsqlite3_result_value = sqlite3_result_value(pCtx, pValue)
End Function

Public Function vbsqlite3_result_zeroblob(ByVal pCtx As OLE_HANDLE, ByVal n As Long) As Long
    vbsqlite3_result_zeroblob = sqlite3_result_zeroblob(pCtx, n)
End Function

Public Function vbsqlite3_result_zeroblob64(ByVal pCtx As OLE_HANDLE, ByVal n As Currency) As Long
    vbsqlite3_result_zeroblob64 = sqlite3_result_zeroblob64(pCtx, n)
End Function

Public Function vbsqlite3_result_error_code(ByVal pCtx As OLE_HANDLE, ByVal errCode As Long) As Long
    vbsqlite3_result_error_code = sqlite3_result_error_code(pCtx, errCode)
End Function

Public Function vbsqlite3_result_error_toobig(ByVal pCtx As OLE_HANDLE) As Long
    vbsqlite3_result_error_toobig = sqlite3_result_error_toobig(pCtx)
End Function

Public Function vbsqlite3_result_error_nomem(ByVal pCtx As OLE_HANDLE) As Long
    vbsqlite3_result_error_nomem = sqlite3_result_error_nomem(pCtx)
End Function

Public Function vbsqlite3_step(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_step = sqlite3_step(pStmt)
End Function

Public Function vbsqlite3_user_data(ByVal p As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_user_data = sqlite3_user_data(p)
End Function

Public Function vbsqlite3_context_db_handle(ByVal p As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_context_db_handle = sqlite3_context_db_handle(p)
End Function

Public Function vbsqlite3_aggregate_context(ByVal p As OLE_HANDLE, ByVal nByte As Long) As OLE_HANDLE
    vbsqlite3_aggregate_context = sqlite3_aggregate_context(p, nByte)
End Function

Public Function vbsqlite3_get_auxdata(ByVal pCtx As OLE_HANDLE, ByVal iArg As Long) As OLE_HANDLE
    vbsqlite3_get_auxdata = sqlite3_get_auxdata(pCtx, iArg)
End Function

Public Function vbsqlite3_set_auxdata(ByVal pCtx As OLE_HANDLE, ByVal iArg As Long, ByVal pAux As OLE_HANDLE, ByVal xDelete As OLE_HANDLE) As Long
    vbsqlite3_set_auxdata = sqlite3_set_auxdata(pCtx, iArg, pAux, xDelete)
End Function

Public Function vbsqlite3_aggregate_count(ByVal p As OLE_HANDLE) As Long
    vbsqlite3_aggregate_count = sqlite3_aggregate_count(p)
End Function

Public Function vbsqlite3_column_count(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_column_count = sqlite3_column_count(pStmt)
End Function

Public Function vbsqlite3_data_count(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_data_count = sqlite3_data_count(pStmt)
End Function

Public Function vbsqlite3_column_blob(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As OLE_HANDLE
    vbsqlite3_column_blob = sqlite3_column_blob(pStmt, i)
End Function

Public Function vbsqlite3_column_bytes(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
    vbsqlite3_column_bytes = sqlite3_column_bytes(pStmt, i)
End Function

Public Function vbsqlite3_column_bytes16(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
    vbsqlite3_column_bytes16 = sqlite3_column_bytes16(pStmt, i)
End Function

Public Function vbsqlite3_column_double(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Double
    vbsqlite3_column_double = sqlite3_column_double(pStmt, i)
End Function

Public Function vbsqlite3_column_int(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
    vbsqlite3_column_int = sqlite3_column_int(pStmt, i)
End Function

Public Function vbsqlite3_column_int64(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Currency
    vbsqlite3_column_int64 = sqlite3_column_int64(pStmt, i)
End Function

Public Function vbsqlite3_column_text(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As OLE_HANDLE
    vbsqlite3_column_text = sqlite3_column_text(pStmt, i)
End Function

Public Function vbsqlite3_column_value(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As OLE_HANDLE
    vbsqlite3_column_value = sqlite3_column_value(pStmt, i)
End Function

Public Function vbsqlite3_column_text16(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As OLE_HANDLE
    vbsqlite3_column_text16 = sqlite3_column_text16(pStmt, i)
End Function

Public Function vbsqlite3_column_type(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
    vbsqlite3_column_type = sqlite3_column_type(pStmt, i)
End Function

Public Function vbsqlite3_column_name(ByVal pStmt As OLE_HANDLE, ByVal N As Long) As Long
    vbsqlite3_column_name = sqlite3_column_name(pStmt, N)
End Function

Public Function vbsqlite3_column_name16(ByVal pStmt As OLE_HANDLE, ByVal N As Long) As OLE_HANDLE
    vbsqlite3_column_name16 = sqlite3_column_name16(pStmt, N)
End Function

Public Function vbsqlite3_column_decltype(ByVal pStmt As OLE_HANDLE, ByVal N As Long) As Long
    vbsqlite3_column_decltype = sqlite3_column_decltype(pStmt, N)
End Function

Public Function vbsqlite3_column_decltype16(ByVal pStmt As OLE_HANDLE, ByVal N As Long) As OLE_HANDLE
    vbsqlite3_column_decltype16 = sqlite3_column_decltype16(pStmt, N)
End Function

Public Function vbsqlite3_bind_blob(ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal zData As OLE_HANDLE, ByVal nData As Long, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_bind_blob = sqlite3_bind_blob(pStmt, i, zData, nData, xDel)
End Function

Public Function vbsqlite3_bind_blob64(ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal zData As OLE_HANDLE, ByVal nData As Currency, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_bind_blob64 = sqlite3_bind_blob64(pStmt, i, zData, nData, xDel)
End Function

Public Function vbsqlite3_bind_double(ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal rValue As Double) As Long
    vbsqlite3_bind_double = sqlite3_bind_double(pStmt, i, rValue)
End Function

Public Function vbsqlite3_bind_int(ByVal p As OLE_HANDLE, ByVal i As Long, ByVal iValue As Long) As Long
    vbsqlite3_bind_int = sqlite3_bind_int(p, i, iValue)
End Function

Public Function vbsqlite3_bind_int64(ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal iValue As Currency) As Long
    vbsqlite3_bind_int64 = sqlite3_bind_int64(pStmt, i, iValue)
End Function

Public Function vbsqlite3_bind_null(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
    vbsqlite3_bind_null = sqlite3_bind_null(pStmt, i)
End Function

Public Function vbsqlite3_bind_text(ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal zData As Long, ByVal nData As Long, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_bind_text = sqlite3_bind_text(pStmt, i, zData, nData, xDel)
End Function

Public Function vbsqlite3_bind_text64(ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal zData As Long, ByVal nData As Currency, ByVal xDel As OLE_HANDLE, ByVal enc As Long) As Long
    vbsqlite3_bind_text64 = sqlite3_bind_text64(pStmt, i, zData, nData, xDel, enc)
End Function

Public Function vbsqlite3_bind_text16(ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal zData As OLE_HANDLE, ByVal nData As Long, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_bind_text16 = sqlite3_bind_text16(pStmt, i, zData, nData, xDel)
End Function

Public Function vbsqlite3_bind_value(ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal pValue As OLE_HANDLE) As Long
    vbsqlite3_bind_value = sqlite3_bind_value(pStmt, i, pValue)
End Function

Public Function vbsqlite3_bind_zeroblob(ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal n As Long) As Long
    vbsqlite3_bind_zeroblob = sqlite3_bind_zeroblob(pStmt, i, n)
End Function

Public Function vbsqlite3_bind_zeroblob64(ByVal pStmt As OLE_HANDLE, ByVal i As Long, ByVal n As Currency) As Long
    vbsqlite3_bind_zeroblob64 = sqlite3_bind_zeroblob64(pStmt, i, n)
End Function

Public Function vbsqlite3_bind_parameter_count(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_bind_parameter_count = sqlite3_bind_parameter_count(pStmt)
End Function

Public Function vbsqlite3_bind_parameter_name(ByVal pStmt As OLE_HANDLE, ByVal i As Long) As Long
    vbsqlite3_bind_parameter_name = sqlite3_bind_parameter_name(pStmt, i)
End Function

Public Function vbsqlite3_bind_parameter_index(ByVal pStmt As OLE_HANDLE, ByVal zName As Long) As Long
    vbsqlite3_bind_parameter_index = sqlite3_bind_parameter_index(pStmt, zName)
End Function

Public Function vbsqlite3_transfer_bindings(ByVal pFromStmt As OLE_HANDLE, ByVal pToStmt As OLE_HANDLE) As Long
    vbsqlite3_transfer_bindings = sqlite3_transfer_bindings(pFromStmt, pToStmt)
End Function

Public Function vbsqlite3_db_handle(ByVal pStmt As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_db_handle = sqlite3_db_handle(pStmt)
End Function

Public Function vbsqlite3_stmt_readonly(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_stmt_readonly = sqlite3_stmt_readonly(pStmt)
End Function

Public Function vbsqlite3_stmt_busy(ByVal pStmt As OLE_HANDLE) As Long
    vbsqlite3_stmt_busy = sqlite3_stmt_busy(pStmt)
End Function

Public Function vbsqlite3_next_stmt(ByVal pDb As OLE_HANDLE, ByVal pStmt As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_next_stmt = sqlite3_next_stmt(pDb, pStmt)
End Function

Public Function vbsqlite3_stmt_status(ByVal pStmt As OLE_HANDLE, ByVal op As Long, ByVal resetFlag As Long) As Long
    vbsqlite3_stmt_status = sqlite3_stmt_status(pStmt, op, resetFlag)
End Function

Public Function vbsqlite3_value_numeric_type(ByVal pVal As OLE_HANDLE) As Long
    vbsqlite3_value_numeric_type = sqlite3_value_numeric_type(pVal)
End Function

Public Function vbsqlite3_blob_open(ByVal db As OLE_HANDLE, ByVal zDb As Long, ByVal zTable As Long, ByVal zColumn As Long, ByVal iRow As Currency, ByVal flags As Long, ByVal ppBlob As OLE_HANDLE) As Long
    vbsqlite3_blob_open = sqlite3_blob_open(db, zDb, zTable, zColumn, iRow, flags, ppBlob)
End Function

Public Function vbsqlite3_blob_close(ByVal pBlob As OLE_HANDLE) As Long
    vbsqlite3_blob_close = sqlite3_blob_close(pBlob)
End Function

Public Function vbsqlite3_blob_read(ByVal pBlob As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal iOffset As Long) As Long
    vbsqlite3_blob_read = sqlite3_blob_read(pBlob, z, n, iOffset)
End Function

Public Function vbsqlite3_blob_write(ByVal pBlob As OLE_HANDLE, ByVal z As OLE_HANDLE, ByVal n As Long, ByVal iOffset As Long) As Long
    vbsqlite3_blob_write = sqlite3_blob_write(pBlob, z, n, iOffset)
End Function

Public Function vbsqlite3_blob_bytes(ByVal pBlob As OLE_HANDLE) As Long
    vbsqlite3_blob_bytes = sqlite3_blob_bytes(pBlob)
End Function

Public Function vbsqlite3_blob_reopen(ByVal pBlob As OLE_HANDLE, ByVal iRow As Currency) As Long
    vbsqlite3_blob_reopen = sqlite3_blob_reopen(pBlob, iRow)
End Function

Public Function vbsqlite3_set_authorizer(ByVal db As OLE_HANDLE, ByVal xAuth As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As Long
    vbsqlite3_set_authorizer = sqlite3_set_authorizer(db, xAuth, pArg)
End Function

Public Function vbsqlite3_strglob(ByVal zGlobPattern As Long, ByVal zString As Long) As Long
    vbsqlite3_strglob = sqlite3_strglob(zGlobPattern, zString)
End Function

Public Function vbsqlite3_strlike(ByVal zPattern As Long, ByVal zStr As Long, ByVal esc As Long) As Long
    vbsqlite3_strlike = sqlite3_strlike(zPattern, zStr, esc)
End Function

Public Function vbsqlite3_exec(ByVal db As OLE_HANDLE, ByVal zSql As Long, ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE, ByVal pzErrMsg As OLE_HANDLE) As Long
    vbsqlite3_exec = sqlite3_exec(db, zSql, xCallback, pArg, pzErrMsg)
End Function

Public Function vbsqlite3_load_extension(ByVal db As OLE_HANDLE, ByVal zFile As Long, ByVal zProc As Long, ByVal pzErrMsg As OLE_HANDLE) As Long
    vbsqlite3_load_extension = sqlite3_load_extension(db, zFile, zProc, pzErrMsg)
End Function

Public Function vbsqlite3_enable_load_extension(ByVal db As OLE_HANDLE, ByVal onoff As Long) As Long
    vbsqlite3_enable_load_extension = sqlite3_enable_load_extension(db, onoff)
End Function

Public Function vbsqlite3_auto_extension(ByVal xInit As OLE_HANDLE) As Long
    vbsqlite3_auto_extension = sqlite3_auto_extension(xInit)
End Function

Public Function vbsqlite3_cancel_auto_extension(ByVal xInit As OLE_HANDLE) As Long
    vbsqlite3_cancel_auto_extension = sqlite3_cancel_auto_extension(xInit)
End Function

Public Function vbsqlite3_reset_auto_extension() As Long
    vbsqlite3_reset_auto_extension = sqlite3_reset_auto_extension()
End Function

Public Function vbsqlite3_prepare(ByVal db As OLE_HANDLE, ByVal zSql As Long, ByVal nBytes As Long, ByVal ppStmt As OLE_HANDLE, ByVal pzTail As OLE_HANDLE) As Long
    vbsqlite3_prepare = sqlite3_prepare(db, zSql, nBytes, ppStmt, pzTail)
End Function

Public Function vbsqlite3_prepare_v2(ByVal db As OLE_HANDLE, ByVal zSql As Long, ByVal nBytes As Long, ByVal ppStmt As OLE_HANDLE, ByVal pzTail As OLE_HANDLE) As Long
    vbsqlite3_prepare_v2 = sqlite3_prepare_v2(db, zSql, nBytes, ppStmt, pzTail)
End Function

Public Function vbsqlite3_prepare16(ByVal db As OLE_HANDLE, ByVal zSql As OLE_HANDLE, ByVal nBytes As Long, ByVal ppStmt As OLE_HANDLE, ByVal pzTail As OLE_HANDLE) As Long
    vbsqlite3_prepare16 = sqlite3_prepare16(db, zSql, nBytes, ppStmt, pzTail)
End Function

Public Function vbsqlite3_prepare16_v2(ByVal db As OLE_HANDLE, ByVal zSql As OLE_HANDLE, ByVal nBytes As Long, ByVal ppStmt As OLE_HANDLE, ByVal pzTail As OLE_HANDLE) As Long
    vbsqlite3_prepare16_v2 = sqlite3_prepare16_v2(db, zSql, nBytes, ppStmt, pzTail)
End Function

Public Function vbsqlite3_get_table(ByVal db As OLE_HANDLE, ByVal zSql As Long, ByVal pazResult As OLE_HANDLE, ByVal pnRow As OLE_HANDLE, ByVal pnColumn As OLE_HANDLE, ByVal pzErrMsg As OLE_HANDLE) As Long
    vbsqlite3_get_table = sqlite3_get_table(db, zSql, pazResult, pnRow, pnColumn, pzErrMsg)
End Function

Public Function vbsqlite3_free_table(ByVal azResult As OLE_HANDLE) As Long
    vbsqlite3_free_table = sqlite3_free_table(azResult)
End Function

Public Function vbsqlite3_create_module(ByVal db As OLE_HANDLE, ByVal zName As Long, ByVal pModule As OLE_HANDLE, ByVal pAux As OLE_HANDLE) As Long
    vbsqlite3_create_module = sqlite3_create_module(db, zName, pModule, pAux)
End Function

Public Function vbsqlite3_create_module_v2(ByVal db As OLE_HANDLE, ByVal zName As Long, ByVal pModule As OLE_HANDLE, ByVal pAux As OLE_HANDLE, ByVal xDestroy As OLE_HANDLE) As Long
    vbsqlite3_create_module_v2 = sqlite3_create_module_v2(db, zName, pModule, pAux, xDestroy)
End Function

Public Function vbsqlite3_declare_vtab(ByVal db As OLE_HANDLE, ByVal zCreateTable As Long) As Long
    vbsqlite3_declare_vtab = sqlite3_declare_vtab(db, zCreateTable)
End Function

Public Function vbsqlite3_vtab_on_conflict(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_vtab_on_conflict = sqlite3_vtab_on_conflict(db)
End Function

Public Function vbsqlite3_complete(ByVal zSql As Long) As Long
    vbsqlite3_complete = sqlite3_complete(zSql)
End Function

Public Function vbsqlite3_complete16(ByVal zSql As OLE_HANDLE) As Long
    vbsqlite3_complete16 = sqlite3_complete16(zSql)
End Function

Public Function vbsqlite3_libversion() As Long
    vbsqlite3_libversion = sqlite3_libversion()
End Function

Public Function vbsqlite3_sourceid() As Long
    vbsqlite3_sourceid = sqlite3_sourceid()
End Function

Public Function vbsqlite3_libversion_number() As Long
    vbsqlite3_libversion_number = sqlite3_libversion_number()
End Function

Public Function vbsqlite3_threadsafe() As Long
    vbsqlite3_threadsafe = sqlite3_threadsafe()
End Function

Public Function vbsqlite3_initialize() As Long
    vbsqlite3_initialize = sqlite3_initialize()
End Function

Public Function vbsqlite3_shutdown() As Long
    vbsqlite3_shutdown = sqlite3_shutdown()
End Function

Public Function vbsqlite3_db_mutex(ByVal db As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_db_mutex = sqlite3_db_mutex(db)
End Function

Public Function vbsqlite3_db_release_memory(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_db_release_memory = sqlite3_db_release_memory(db)
End Function

Public Function vbsqlite3_db_cacheflush(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_db_cacheflush = sqlite3_db_cacheflush(db)
End Function

Public Function vbsqlite3_last_insert_rowid(ByVal db As OLE_HANDLE) As Currency
    vbsqlite3_last_insert_rowid = sqlite3_last_insert_rowid(db)
End Function

Public Function vbsqlite3_changes(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_changes = sqlite3_changes(db)
End Function

Public Function vbsqlite3_total_changes(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_total_changes = sqlite3_total_changes(db)
End Function

Public Function vbsqlite3_close(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_close = sqlite3_close(db)
End Function

Public Function vbsqlite3_close_v2(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_close_v2 = sqlite3_close_v2(db)
End Function

Public Function vbsqlite3_busy_handler(ByVal db As OLE_HANDLE, ByVal xBusy As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As Long
    vbsqlite3_busy_handler = sqlite3_busy_handler(db, xBusy, pArg)
End Function

Public Function vbsqlite3_progress_handler(ByVal db As OLE_HANDLE, ByVal nOps As Long, ByVal xProgress As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As Long
    vbsqlite3_progress_handler = sqlite3_progress_handler(db, nOps, xProgress, pArg)
End Function

Public Function vbsqlite3_busy_timeout(ByVal db As OLE_HANDLE, ByVal ms As Long) As Long
    vbsqlite3_busy_timeout = sqlite3_busy_timeout(db, ms)
End Function

Public Function vbsqlite3_interrupt(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_interrupt = sqlite3_interrupt(db)
End Function

Public Function vbsqlite3_create_function(ByVal db As OLE_HANDLE, ByVal zFunc As Long, ByVal nArg As Long, ByVal enc As Long, ByVal p As OLE_HANDLE, ByVal xSFunc As OLE_HANDLE, ByVal xStep As OLE_HANDLE, ByVal xFinal As OLE_HANDLE) As Long
    vbsqlite3_create_function = sqlite3_create_function(db, zFunc, nArg, enc, p, xSFunc, xStep, xFinal)
End Function

Public Function vbsqlite3_create_function_v2(ByVal db As OLE_HANDLE, ByVal zFunc As Long, ByVal nArg As Long, ByVal enc As Long, ByVal p As OLE_HANDLE, ByVal xSFunc As OLE_HANDLE, ByVal xStep As OLE_HANDLE, ByVal xFinal As OLE_HANDLE, ByVal xDestroy As OLE_HANDLE) As Long
    vbsqlite3_create_function_v2 = sqlite3_create_function_v2(db, zFunc, nArg, enc, p, xSFunc, xStep, xFinal, xDestroy)
End Function

Public Function vbsqlite3_create_function16(ByVal db As OLE_HANDLE, ByVal zFunctionName As OLE_HANDLE, ByVal nArg As Long, ByVal eTextRep As Long, ByVal p As OLE_HANDLE, ByVal xSFunc As OLE_HANDLE, ByVal xStep As OLE_HANDLE, ByVal xFinal As OLE_HANDLE) As Long
    vbsqlite3_create_function16 = sqlite3_create_function16(db, zFunctionName, nArg, eTextRep, p, xSFunc, xStep, xFinal)
End Function

Public Function vbsqlite3_overload_function(ByVal db As OLE_HANDLE, ByVal zName As Long, ByVal nArg As Long) As Long
    vbsqlite3_overload_function = sqlite3_overload_function(db, zName, nArg)
End Function

Public Function vbsqlite3_trace(ByVal db As OLE_HANDLE, ByVal xTrace As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_trace = sqlite3_trace(db, xTrace, pArg)
End Function

Public Function vbsqlite3_profile(ByVal db As OLE_HANDLE, ByVal xProfile As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_profile = sqlite3_profile(db, xProfile, pArg)
End Function

Public Function vbsqlite3_commit_hook(ByVal db As OLE_HANDLE, ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_commit_hook = sqlite3_commit_hook(db, xCallback, pArg)
End Function

Public Function vbsqlite3_update_hook(ByVal db As OLE_HANDLE, ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_update_hook = sqlite3_update_hook(db, xCallback, pArg)
End Function

Public Function vbsqlite3_rollback_hook(ByVal db As OLE_HANDLE, ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_rollback_hook = sqlite3_rollback_hook(db, xCallback, pArg)
End Function

Public Function vbsqlite3_wal_autocheckpoint(ByVal db As OLE_HANDLE, ByVal nFrame As Long) As Long
    vbsqlite3_wal_autocheckpoint = sqlite3_wal_autocheckpoint(db, nFrame)
End Function

Public Function vbsqlite3_wal_hook(ByVal db As OLE_HANDLE, ByVal xCallback As OLE_HANDLE, ByVal pArg As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_wal_hook = sqlite3_wal_hook(db, xCallback, pArg)
End Function

Public Function vbsqlite3_wal_checkpoint_v2(ByVal db As OLE_HANDLE, ByVal zDb As Long, ByVal eMode As Long, ByVal pnLog As OLE_HANDLE, ByVal pnCkpt As OLE_HANDLE) As Long
    vbsqlite3_wal_checkpoint_v2 = sqlite3_wal_checkpoint_v2(db, zDb, eMode, pnLog, pnCkpt)
End Function

Public Function vbsqlite3_wal_checkpoint(ByVal db As OLE_HANDLE, ByVal zDb As Long) As Long
    vbsqlite3_wal_checkpoint = sqlite3_wal_checkpoint(db, zDb)
End Function

Public Function vbsqlite3_errmsg(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_errmsg = sqlite3_errmsg(db)
End Function

Public Function vbsqlite3_errmsg16(ByVal db As OLE_HANDLE) As OLE_HANDLE
    vbsqlite3_errmsg16 = sqlite3_errmsg16(db)
End Function

Public Function vbsqlite3_errcode(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_errcode = sqlite3_errcode(db)
End Function

Public Function vbsqlite3_extended_errcode(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_extended_errcode = sqlite3_extended_errcode(db)
End Function

Public Function vbsqlite3_errstr(ByVal rc As Long) As Long
    vbsqlite3_errstr = sqlite3_errstr(rc)
End Function

Public Function vbsqlite3_limit(ByVal db As OLE_HANDLE, ByVal limitId As Long, ByVal newLimit As Long) As Long
    vbsqlite3_limit = sqlite3_limit(db, limitId, newLimit)
End Function

Public Function vbsqlite3_open(ByVal zFilename As Long, ByVal ppDb As OLE_HANDLE) As Long
    vbsqlite3_open = sqlite3_open(zFilename, ppDb)
End Function

Public Function vbsqlite3_open_v2(ByVal filename As Long, ByVal ppDb As OLE_HANDLE, ByVal flags As Long, ByVal zVfs As Long) As Long
    vbsqlite3_open_v2 = sqlite3_open_v2(filename, ppDb, flags, zVfs)
End Function

Public Function vbsqlite3_open16(ByVal zFilename As OLE_HANDLE, ByVal ppDb As OLE_HANDLE) As Long
    vbsqlite3_open16 = sqlite3_open16(zFilename, ppDb)
End Function

Public Function vbsqlite3_create_collation(ByVal db As OLE_HANDLE, ByVal zName As Long, ByVal enc As Long, ByVal pCtx As OLE_HANDLE, ByVal xCompare As OLE_HANDLE) As Long
    vbsqlite3_create_collation = sqlite3_create_collation(db, zName, enc, pCtx, xCompare)
End Function

Public Function vbsqlite3_create_collation_v2(ByVal db As OLE_HANDLE, ByVal zName As Long, ByVal enc As Long, ByVal pCtx As OLE_HANDLE, ByVal xCompare As OLE_HANDLE, ByVal xDel As OLE_HANDLE) As Long
    vbsqlite3_create_collation_v2 = sqlite3_create_collation_v2(db, zName, enc, pCtx, xCompare, xDel)
End Function

Public Function vbsqlite3_create_collation16(ByVal db As OLE_HANDLE, ByVal zName As OLE_HANDLE, ByVal enc As Long, ByVal pCtx As OLE_HANDLE, ByVal xCompare As OLE_HANDLE) As Long
    vbsqlite3_create_collation16 = sqlite3_create_collation16(db, zName, enc, pCtx, xCompare)
End Function

Public Function vbsqlite3_collation_needed(ByVal db As OLE_HANDLE, ByVal pCollNeededArg As OLE_HANDLE, ByVal xCollNeeded As OLE_HANDLE) As Long
    vbsqlite3_collation_needed = sqlite3_collation_needed(db, pCollNeededArg, xCollNeeded)
End Function

Public Function vbsqlite3_collation_needed16(ByVal db As OLE_HANDLE, ByVal pCollNeededArg As OLE_HANDLE, ByVal xCollNeeded16 As OLE_HANDLE) As Long
    vbsqlite3_collation_needed16 = sqlite3_collation_needed16(db, pCollNeededArg, xCollNeeded16)
End Function

Public Function vbsqlite3_global_recover() As Long
    vbsqlite3_global_recover = sqlite3_global_recover()
End Function

Public Function vbsqlite3_get_autocommit(ByVal db As OLE_HANDLE) As Long
    vbsqlite3_get_autocommit = sqlite3_get_autocommit(db)
End Function

Public Function vbsqlite3_thread_cleanup() As Long
    vbsqlite3_thread_cleanup = sqlite3_thread_cleanup()
End Function

Public Function vbsqlite3_table_column_metadata(ByVal db As OLE_HANDLE, ByVal zDbName As Long, ByVal zTableName As Long, ByVal zColumnName As Long, ByVal pzDataType As OLE_HANDLE, ByVal pzCollSeq As OLE_HANDLE, ByVal pNotNull As OLE_HANDLE, ByVal pPrimaryKey As OLE_HANDLE, ByVal pAutoinc As OLE_HANDLE) As Long
    vbsqlite3_table_column_metadata = sqlite3_table_column_metadata(db, zDbName, zTableName, zColumnName, pzDataType, pzCollSeq, pNotNull, pPrimaryKey, pAutoinc)
End Function

Public Function vbsqlite3_sleep(ByVal ms As Long) As Long
    vbsqlite3_sleep = sqlite3_sleep(ms)
End Function

Public Function vbsqlite3_extended_result_codes(ByVal db As OLE_HANDLE, ByVal onoff As Long) As Long
    vbsqlite3_extended_result_codes = sqlite3_extended_result_codes(db, onoff)
End Function

Public Function vbsqlite3_file_control(ByVal db As OLE_HANDLE, ByVal zDbName As Long, ByVal op As Long, ByVal pArg As OLE_HANDLE) As Long
    vbsqlite3_file_control = sqlite3_file_control(db, zDbName, op, pArg)
End Function

Public Function vbsqlite3_uri_parameter(ByVal zFilename As Long, ByVal zParam As Long) As Long
    vbsqlite3_uri_parameter = sqlite3_uri_parameter(zFilename, zParam)
End Function

Public Function vbsqlite3_uri_boolean(ByVal zFilename As Long, ByVal zParam As Long, ByVal bDflt As Long) As Long
    vbsqlite3_uri_boolean = sqlite3_uri_boolean(zFilename, zParam, bDflt)
End Function

Public Function vbsqlite3_uri_int64(ByVal zFilename As Long, ByVal zParam As Long, ByVal bDflt As Currency) As Currency
    vbsqlite3_uri_int64 = sqlite3_uri_int64(zFilename, zParam, bDflt)
End Function

Public Function vbsqlite3_db_filename(ByVal db As OLE_HANDLE, ByVal zDbName As Long) As Long
    vbsqlite3_db_filename = sqlite3_db_filename(db, zDbName)
End Function

Public Function vbsqlite3_db_readonly(ByVal db As OLE_HANDLE, ByVal zDbName As Long) As Long
    vbsqlite3_db_readonly = sqlite3_db_readonly(db, zDbName)
End Function

Public Function vbsqlite3_rtree_geometry_callback(ByVal db As OLE_HANDLE, ByVal zGeom As Long, ByVal xGeom As OLE_HANDLE, ByVal pContext As OLE_HANDLE) As Long
    vbsqlite3_rtree_geometry_callback = sqlite3_rtree_geometry_callback(db, zGeom, xGeom, pContext)
End Function

Public Function vbsqlite3_rtree_query_callback(ByVal db As OLE_HANDLE, ByVal zQueryFunc As Long, ByVal xQueryFunc As OLE_HANDLE, ByVal pContext As OLE_HANDLE, ByVal xDestructor As OLE_HANDLE) As Long
    vbsqlite3_rtree_query_callback = sqlite3_rtree_query_callback(db, zQueryFunc, xQueryFunc, pContext, xDestructor)
End Function
